AllCops:
  Exclude:
    - 'ruby_paypal_nvp.gemspec'
    - 'spec/**/*'
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 89

Documentation:
  Enabled: false

Naming/VariableName:
  Enabled: false
